# Generated by Django 4.2.1 on 2023-05-15 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Confirm',
            new_name='confirm',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Email_confirmed',
            new_name='email_confirmed',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='FindUs',
            new_name='find_us',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Phone_Confirmed',
            new_name='phone_confirmed',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='RegIp',
            new_name='reg_ip',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Secret_Answer_1',
            new_name='secret_answer_1',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Secret_Answer_2',
            new_name='secret_answer_2',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Secret_Question_1',
            new_name='secret_question_1',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Secret_Question_2',
            new_name='secret_question_2',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Street',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='UserCode',
            new_name='user_code',
        ),
    ]
