# Generated by Django 4.2.1 on 2023-05-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Salt',
            new_name='salt',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Sex',
            new_name='sex',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='State',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='member',
            name='access_status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='ref_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='toured',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
