# Generated by Django 4.2.1 on 2023-05-15 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_confirm_member_confirm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='dedicatedaccountNumber',
            new_name='dedicated_account_number',
        ),
    ]
