# Generated by Django 4.2.1 on 2023-05-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_member_pg_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='block_funds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
